name: HyperHDR CI Build
on:
  push:
    branches-ignore:
      - 'gh-pages'
      - 'docker-ci'
    tags:
      - '*'

jobs:

######################
###### Linux #########
######################

  Linux:
    name: ${{ matrix.dockerName }}
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        dockerImage: [ x86_64, armv6l, armv7l ]
        include:
          - dockerImage: x86_64
            dockerName: Debian Buster (x86_64)
            platform: x11
          - dockerImage: armv6l
            dockerName: Debian Buster (Raspberry Pi 1 & 2 & ZERO)
            platform: rpi         
          - dockerImage: armv7l
            dockerName: Debian Buster (Raspberry Pi 3 & 4)
            platform: rpi

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true

      # build process
      - name: Build packages
        env:
          DOCKER_IMAGE: ${{ matrix.dockerImage }}
          DOCKER_TAG: buster
          DOCKER_NAME: ${{ matrix.dockerName }}
          PLATFORM: ${{ matrix.platform }}
        shell: bash
        run: ./.ci/ci_build.sh

      # upload artifacts (only on tagged commit)
      - name: Upload artifacts
        if: startsWith(github.event.ref, 'refs/tags')
        uses: actions/upload-artifact@v2
        with:
          path: deploy/Hyper*

      # Upload artifacts from commit
      - name: Upload artifacts from commit
        if: (startsWith(github.event.ref, 'refs/tags') != true)
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.dockerImage }}
          path: deploy/Hyper*
          
######################
###### Windows #######
######################

  windows:
    name: Windows
    runs-on: windows-latest
    env:
      VCINSTALLDIR: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC'
      QT_VERSION: 5.15.0
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          submodules: true

      - name: Cache Qt
        uses: actions/cache@v2
        id: cache-qt-windows
        with:
          path: ${{ runner.workspace }}/Qt
          key: ${{ runner.os }}-Qt.${{ env.QT_VERSION }}

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{ env.QT_VERSION }}
          target: 'desktop'
          arch: 'win64_msvc2019_64'
          cached: ${{ steps.cache-qt-windows.outputs.cache-hit }}

      - name: Cache Chocolatey downloads
        uses: actions/cache@v2
        with:
          path: C:\Users\runneradmin\AppData\Local\Temp\chocolatey
          key: ${{ runner.os }}-chocolatey

      - name: "Remove Redistributable"
        shell: cmd
        run: |
          MsiExec.exe /passive /X{F0C3E5D1-1ADE-321E-8167-68EF0DE699A5}
          MsiExec.exe /passive /X{1D8E6291-B0D5-35EC-8441-6616F567A0F7}

      - name: Install Python, NSIS, OpenSSL, TurboJPG, 7zip
        shell: powershell
        run: |
          choco install --no-progress python nsis openssl 7zip.install -y
      - name: Set up x64 build architecture environment
        shell: cmd
        run: call "${{env.VCINSTALLDIR}}\Auxiliary\Build\vcvars64.bat"

      # Build packages
      - name: Build packages
        env:
          PLATFORM: windows
        shell: bash
        run: ./.ci/ci_build.sh

      # upload artifacts (only on tagged commit)
      - name: Upload artifacts
        if: startsWith(github.event.ref, 'refs/tags')
        uses: actions/upload-artifact@v2
        with:
          path: build/Hyper*
          
      # Upload artifacts from commit
      #- name: Upload artifacts from commit
      #  if: (startsWith(github.event.ref, 'refs/tags') != true)
      #  uses: actions/upload-artifact@v2
      #  with:
      #    name: windows
      #    path: build/Hyper*          
          
################################
###### Publish Releases ########
################################

  publish:
    name: Publish Releases
    if: startsWith(github.event.ref, 'refs/tags')
    needs: [Linux, windows]
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # generate environment variables
      - name: Generate environment variables from version and tag
        run: |
          echo ::set-env name=TAG::${GITHUB_REF/refs\/tags\//}
          echo ::set-env name=VERSION::$(tr -d '\n' < version)
          echo ::set-env name=preRelease::false

      # If version contains alpha or beta, mark draft release as pre-release
      - name: Mark release as pre-release
        if: contains(env.VERSION, 'alpha') || contains(env.VERSION, 'beta')
        run: echo ::set-env name=preRelease::true

      # Download artifacts from previous build process
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          path: artifacts

      # create draft release and upload artifacts
      - name: Create draft release
        uses: softprops/action-gh-release@v1
        with:
          name: HyperHDR ${{ env.VERSION }}
          tag_name: ${{ env.TAG }}
          files: "artifacts/**"
          draft: true
          prerelease: ${{ env.preRelease }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
